# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\\\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x10\n\x08\x64ue_date\x18\x03 \x01(\t\x12\x11\n\tcompleted\x18\x04 \x01(\x08\x12\x12\n\nprior_rank\x18\x05 \x01(\x05\x32\x83\x02\n\x0bTaskService\x12$\n\nCreateTask\x12\n.task.Task\x1a\n.task.Task\x12\x31\n\tListTasks\x12\x16.google.protobuf.Empty\x1a\n.task.Task0\x01\x12\x32\n\x07GetTask\x12\x1b.google.protobuf.Int32Value\x1a\n.task.Task\x12$\n\nUpdateTask\x12\n.task.Task\x1a\n.task.Task\x12\x41\n\nDeleteTask\x12\x1b.google.protobuf.Int32Value\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASK']._serialized_start=81
  _globals['_TASK']._serialized_end=173
  _globals['_TASKSERVICE']._serialized_start=176
  _globals['_TASKSERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
